#!/bin/bash

echo && \
echo 'Testing pac generated by BlackGear/Mono_Pac' && \
cat BlackGear-Mono_Pac.pac include.js performance_test.js > ./test.js && \
node ./test.js && \
echo && \
echo 'Testing pac generated by breakwa11/gfw_whitelist' && \
cat breakwa11-gfw_whitelist.pac include.js performance_test.js > ./test.js && \
node ./test.js && \
echo && \
echo 'Testing pac generated by Leask/flora_pac' && \
cat Leask-Flora_Pac.pac include.js performance_test.js > ./test.js && \
node ./test.js && \
echo && \
echo 'Testing pac generated by Leask/flora_pac-mod' && \
cat Leask-Flora_Pac-mod.pac include.js performance_test.js > ./test.js && \
node ./test.js && \
echo && \
echo 'Testing pac generated by usufu/flora_pac' && \
cat usufu-Flora_Pac.pac include.js performance_test.js > ./test.js && \
node ./test.js && \
echo && \
rm ./test.js
ls -la *.pac
